In [2]:
import pandas as pd

In [ ]:
# Loading the data
path = "Crunchbase\Fintech\FinTechCompanies.csv"
df = pd.read_csv(path)

C:\Users\20193244\AppData\Local\Temp\ipykernel_1944\1239891492.py:2: DtypeWarning: Columns (39,47,111,119) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

In [4]:
df

,Organization Name,Organization Name URL,CB Rank (Organization),Industries,Founded Date,Year,Year.1,Age,Founded Date Precision,Estimated Revenue Range,...,IPqwery - Most Popular Patent Class,IPqwery - Most Popular Trademark Class,Aberdeen - IT Spend,Aberdeen - IT Spend Currency,Aberdeen - IT Spend Currency (in USD),Number of Portfolio Organizations,Number of Investments,Number of Lead Investments,Number of Exits,Number of Exits (IPO)
0,Flutterwave,https://www.crunchbase.com/organization/flutte...,4,"Developer APIs, FinTech, Payments, Software",1/1/2016,2016,2016,4,year,$1M to $10M,...,NaN,NaN,22276.0,USD,22276.0,NaN,NaN,NaN,NaN,NaN
1,Finix,https://www.crunchbase.com/organization/finix-...,5,"Banking, E-Commerce, Financial Services, FinTe...",1/1/2016,2016,2016,4,year,Less than $1M,...,NaN,Insurance; financial affairs,121993.0,USD,121993.0,NaN,NaN,NaN,NaN,NaN
2,Cadre,https://www.crunchbase.com/organization/cadre-2,12,"Financial Services, FinTech, Marketplace, Real...",9/11/2014,2014,2014,6,day,$10M to $50M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Square,https://www.crunchbase.com/organization/square,13,"Finance, FinTech, Hardware, Mobile, Mobile Pay...",2/1/2009,2009,2009,11,day,$1B to $10B,...,Computing; Calculating,Scientific and electric apparatus and instruments,679030661.0,USD,679030661.0,12.0,12,NaN,3.0,3.0
4,Arcus,https://www.crunchbase.com/organization/regalii,17,"Financial Services, FinTech, Mobile, Mobile Pa...",5/1/2013,2013,2013,7,month,$1M to $10M,...,NaN,Scientific and technological services,140176.0,USD,140176.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13389,Luther Wealth Management,https://www.crunchbase.com/organization/luther...,"1,036,559","Financial Services, FinTech, Personal Finance,...",1/8/2018,2018,2018,2,day,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13390,Finobi,https://www.crunchbase.com/organization/finobi,"1,037,444","Financial Services, FinTech, Information Techn...",NaN,1900,1900,120,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13391,CfaTestBank,https://www.crunchbase.com/organization/cfates...,"1,037,488","Education, Financial Services, FinTech, Internet",6/25/2009,2009,2009,11,day,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13392,Shinobi Capital,https://www.crunchbase.com/organization/shinob...,"1,038,416","Blockchain, Cryptocurrency, FinTech, Venture C...",1/1/2018,2018,2018,2,month,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN
13393,Mozacoin,https://www.crunchbase.com/organization/mozacoin,"1,050,361","Bitcoin, Blockchain, Cryptocurrency, Ethereum,...",2/2/2020,2020,2020,0,day,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Printing all the columns to check which columns are needed
columns_list = df.columns.tolist()
for column in columns_list:
    print(column)

Organization Name
Organization Name URL
CB Rank (Organization)
Industries
Founded Date
Year
Year.1
Age
Founded Date Precision
Estimated Revenue Range
Exit Date
Exit Date Precision
Closed Date
Closed Date Precision
Hub Tags
Full Description
Industry Groups
Funding Status
Total Funding Amount
Total Funding Amount Currency
Total Funding Amount Currency (in USD)
Top 5 Investors
Acquired by
Acquired by URL
Announced Date
Announced Date Precision
Operating Status
Headquarters Location
Company Type
Website
Number of Employees
Acquisition Status
Headquarters Regions
Description
Twitter
Facebook
LinkedIn
Contact Email
Phone Number
Number of Articles
Investor Type
Investment Stage
Accelerator Program Type
Accelerator Application Deadline
Accelerator Duration (in weeks)
School Type
School Program
Number of Enrollments
School Method
Number of Founders (Alumni)
Number of Alumni
Founders
Number of Founders
Number of Funding Rounds
Last Funding Date
Last Funding Amount
Last Funding Amount Currency
Last Funding Amount Currency (in USD)
Last Funding Type
Last Equity Funding Amount
Last Equity Funding Amount Currency
Last Equity Funding Amount Currency (in USD)
Last Equity Funding Type
Total Equity Funding Amount
Total Equity Funding Amount Currency
Total Equity Funding Amount Currency (in USD)
Number of Lead Investors
Number of Investors
Number of Acquisitions
Price
Price Currency
Price Currency (in USD)
Acquisition Type
Acquisition Terms
Transaction Name
Transaction Name URL
IPO Status
IPO Date
Delisted Date
Delisted Date Precision
Money Raised at IPO
Money Raised at IPO Currency
Money Raised at IPO Currency (in USD)
Valuation at IPO
Valuation at IPO Currency
Valuation at IPO Currency (in USD)
Stock Symbol
Stock Symbol URL
Stock Exchange
Number of Events
CB Rank (Company)
CB Rank (School)
Trend Score (7 Days)
Trend Score (30 Days)
Trend Score (90 Days)
SimilarWeb - Monthly Visits
SimilarWeb - Average Visits (6 months)
SimilarWeb - Monthly Visits Growth
SimilarWeb - Visit Duration
SimilarWeb - Visit Duration Growth
SimilarWeb - Page Views / Visit
SimilarWeb - Page Views / Visit Growth
SimilarWeb - Bounce Rate
SimilarWeb - Bounce Rate Growth
SimilarWeb - Global Traffic Rank
SimilarWeb - Monthly Rank Change (#)
SimilarWeb - Monthly Rank Growth
BuiltWith - Active Tech Count
Apptopia - Number of Apps
Apptopia - Downloads Last 30 Days
G2 Stack - Total Products Active
IPqwery - Patents Granted
IPqwery - Trademarks Registered
IPqwery - Most Popular Patent Class
IPqwery - Most Popular Trademark Class
Aberdeen - IT Spend
Aberdeen - IT Spend Currency
Aberdeen - IT Spend Currency (in USD)
Number of Portfolio Organizations
Number of Investments
Number of Lead Investments
Number of Exits
Number of Exits (IPO)

In [ ]:
# Filtering the columns based on the hypotheses
filtered_columns = [
    "Organization Name", "CB Rank (Organization)", "Industries", "Founded Date", "Year", "Founded Date Precision", "Estimated Revenue Range", 
    "BuiltWith - Active Tech Count", "G2 Stack - Total Products Active", # For H1
    "SimilarWeb - Monthly Visits Growth", "SimilarWeb - Visit Duration", # For H2
    "IPqwery - Patents Granted", "IPqwery - Trademarks Registered"] # For H3 

# Creating a new dataframe with only these columns
filtered_df = df[filtered_columns]
filtered_df

,Organization Name,CB Rank (Organization),Industries,Founded Date,Year,Founded Date Precision,Estimated Revenue Range,BuiltWith - Active Tech Count,G2 Stack - Total Products Active,SimilarWeb - Monthly Visits Growth,SimilarWeb - Visit Duration,IPqwery - Patents Granted,IPqwery - Trademarks Registered
0,Flutterwave,4,"Developer APIs, FinTech, Payments, Software",1/1/2016,2016,year,$1M to $10M,97.0,25.0,-48.83%,"1,275",NaN,NaN
1,Finix,5,"Banking, E-Commerce, Financial Services, FinTe...",1/1/2016,2016,year,Less than $1M,34.0,23.0,1.64%,150,0,2.0
2,Cadre,12,"Financial Services, FinTech, Marketplace, Real...",9/11/2014,2014,day,$10M to $50M,42.0,19.0,-9.50%,57,NaN,NaN
3,Square,13,"Finance, FinTech, Hardware, Mobile, Mobile Pay...",2/1/2009,2009,day,$1B to $10B,34.0,63.0,6.55%,290,724,49.0
4,Arcus,17,"Financial Services, FinTech, Mobile, Mobile Pa...",5/1/2013,2013,month,$1M to $10M,32.0,NaN,-60.72%,"1,391",0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13389,Luther Wealth Management,"1,036,559","Financial Services, FinTech, Personal Finance,...",1/8/2018,2018,day,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13390,Finobi,"1,037,444","Financial Services, FinTech, Information Techn...",NaN,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13391,CfaTestBank,"1,037,488","Education, Financial Services, FinTech, Internet",6/25/2009,2009,day,NaN,2.0,NaN,NaN,NaN,NaN,NaN
13392,Shinobi Capital,"1,038,416","Blockchain, Cryptocurrency, FinTech, Venture C...",1/1/2018,2018,month,NaN,11.0,NaN,-100%,NaN,NaN,NaN
13393,Mozacoin,"1,050,361","Bitcoin, Blockchain, Cryptocurrency, Ethereum,...",2/2/2020,2020,day,NaN,12.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Checking the nan values for each column
nan_counts = filtered_df.isna().sum()
sorted_nan_counts = nan_counts.sort_values(ascending=False)
sorted_nan_counts_nonzero = sorted_nan_counts[sorted_nan_counts > 0]
for column, count in sorted_nan_counts_nonzero.items():
    print(f"{count}: {column}")

11002: IPqwery - Trademarks Registered
11002: IPqwery - Patents Granted
8262: G2 Stack - Total Products Active
7978: Estimated Revenue Range
6325: SimilarWeb - Visit Duration
4991: SimilarWeb - Monthly Visits Growth
1271: Founded Date
1271: Founded Date Precision
1035: BuiltWith - Active Tech Count

In [ ]:
# Creating a dataframe specifically for H1 where these columns are not nan
df_h1 = filtered_df.dropna(subset=["BuiltWith - Active Tech Count", "G2 Stack - Total Products Active"])
df_h1

,Organization Name,CB Rank (Organization),Industries,Founded Date,Year,Founded Date Precision,Estimated Revenue Range,SimilarWeb - Monthly Visits Growth,SimilarWeb - Visit Duration,IPqwery - Patents Granted,IPqwery - Trademarks Registered,BuiltWith - Active Tech Count,G2 Stack - Total Products Active
0,Flutterwave,4,"Developer APIs, FinTech, Payments, Software",1/1/2016,2016,year,$1M to $10M,-48.83%,"1,275",NaN,NaN,97.0,25.0
1,Finix,5,"Banking, E-Commerce, Financial Services, FinTe...",1/1/2016,2016,year,Less than $1M,1.64%,150,0,2.0,34.0,23.0
2,Cadre,12,"Financial Services, FinTech, Marketplace, Real...",9/11/2014,2014,day,$10M to $50M,-9.50%,57,NaN,NaN,42.0,19.0
3,Square,13,"Finance, FinTech, Hardware, Mobile, Mobile Pay...",2/1/2009,2009,day,$1B to $10B,6.55%,290,724,49.0,34.0,63.0
5,Monzo,33,"Banking, Finance, Financial Services, FinTech",2/1/2015,2015,month,$10M to $50M,15.72%,331,0,21.0,64.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13043,Treecast,"898,998","Artificial Intelligence, Big Data, Financial S...",1/1/2017,2017,day,Less than $1M,NaN,NaN,NaN,NaN,4.0,10.0
13089,Road to Value,"914,549","Business Development, Consulting, Finance, Fin...",1/1/2009,2009,year,$1M to $10M,NaN,NaN,NaN,NaN,4.0,6.0
13139,LoanTraq,"937,807","Finance, FinTech, Mobile, Mobile Payments",6/1/2013,2013,day,$1M to $10M,NaN,NaN,NaN,NaN,5.0,3.0
13334,Gold Tadpole Internet Finance,"1,004,226","B2B, FinTech",NaN,1900,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0
13353,Riovic,"1,014,729","FinTech, Insurance, InsurTech, Life Insurance",1/1/2015,2015,month,$1M to $10M,NaN,NaN,NaN,NaN,11.0,14.0

In [ ]:
# Creating a dataframe specifically for H2 where these columns are not nan
df_h2 = filtered_df.dropna(subset=["SimilarWeb - Monthly Visits Growth", "SimilarWeb - Visit Duration"])
df_h2

,Organization Name,CB Rank (Organization),Industries,Founded Date,Year,Founded Date Precision,Estimated Revenue Range,SimilarWeb - Monthly Visits Growth,SimilarWeb - Visit Duration,IPqwery - Patents Granted,IPqwery - Trademarks Registered,BuiltWith - Active Tech Count,G2 Stack - Total Products Active
0,Flutterwave,4,"Developer APIs, FinTech, Payments, Software",1/1/2016,2016,year,$1M to $10M,-48.83%,"1,275",NaN,NaN,97.0,25.0
1,Finix,5,"Banking, E-Commerce, Financial Services, FinTe...",1/1/2016,2016,year,Less than $1M,1.64%,150,0,2.0,34.0,23.0
2,Cadre,12,"Financial Services, FinTech, Marketplace, Real...",9/11/2014,2014,day,$10M to $50M,-9.50%,57,NaN,NaN,42.0,19.0
3,Square,13,"Finance, FinTech, Hardware, Mobile, Mobile Pay...",2/1/2009,2009,day,$1B to $10B,6.55%,290,724,49.0,34.0,63.0
4,Arcus,17,"Financial Services, FinTech, Mobile, Mobile Pa...",5/1/2013,2013,month,$1M to $10M,-60.72%,"1,391",0,1.0,32.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13059,Chexiao Technology,"902,873","Auto Insurance, Financial Services, FinTech",NaN,1900,NaN,NaN,-27.38%,"2,528",NaN,NaN,10.0,NaN
13077,Cashway,"909,958","Finance, Financial Services, FinTech, Intellig...",1/1/2004,2004,day,NaN,6.63%,945,NaN,NaN,16.0,NaN
13084,Finance and Coffee,"912,247","Apps, Communities, Financial Services, FinTech...",6/1/2017,2017,day,NaN,295.24%,35,NaN,NaN,26.0,NaN
13094,eTaxCanada,"916,471","Finance, Financial Services, FinTech, Wealth M...",NaN,1900,NaN,NaN,-95.24%,15,NaN,NaN,7.0,NaN
13108,Boilingice,"922,083","Financial Services, FinTech",7/1/2002,2002,day,NaN,-88.76%,5,NaN,NaN,13.0,NaN

In [ ]:
# Creating a dataframe specifically for H3 where these columns are not nan
df_h3 = filtered_df.dropna(subset=["IPqwery - Patents Granted", "IPqwery - Trademarks Registered"])
df_h3

,Organization Name,CB Rank (Organization),Industries,Founded Date,Year,Founded Date Precision,Estimated Revenue Range,SimilarWeb - Monthly Visits Growth,SimilarWeb - Visit Duration,IPqwery - Patents Granted,IPqwery - Trademarks Registered,BuiltWith - Active Tech Count,G2 Stack - Total Products Active
1,Finix,5,"Banking, E-Commerce, Financial Services, FinTe...",1/1/2016,2016,year,Less than $1M,1.64%,150,0,2.0,34.0,23.0
3,Square,13,"Finance, FinTech, Hardware, Mobile, Mobile Pay...",2/1/2009,2009,day,$1B to $10B,6.55%,290,724,49.0,34.0,63.0
4,Arcus,17,"Financial Services, FinTech, Mobile, Mobile Pa...",5/1/2013,2013,month,$1M to $10M,-60.72%,"1,391",0,1.0,32.0,NaN
5,Monzo,33,"Banking, Finance, Financial Services, FinTech",2/1/2015,2015,month,$10M to $50M,15.72%,331,0,21.0,64.0,26.0
6,TransferWise,36,"Finance, Financial Services, FinTech, Payments...",1/1/2011,2011,year,$100M to $500M,1.59%,340,0,22.0,79.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12624,Schmidt + Funk Financial Services,"748,634","Financial Services, FinTech, Insurance",NaN,1900,NaN,NaN,-91.07%,3,0.0,1.0,27.0,NaN
12635,Coruja Fiança Locatícia,"750,884","B2C, Construction, Consumer, Finance, FinTech",NaN,1900,NaN,NaN,NaN,NaN,0.0,0.0,18.0,NaN
12772,Angeltips,"798,208","Association, Finance, FinTech, Non Profit",1/1/1999,1999,year,NaN,-100%,NaN,0.0,1.0,14.0,NaN
12786,MuniMatch Corporation,"804,924",FinTech,1/2/2015,2015,day,$1M to $10M,NaN,NaN,0.0,8.0,1.0,NaN
13112,Decision Technologies,"922,735","Finance, Financial Services, FinTech",1/1/2004,2004,year,NaN,NaN,NaN,1.0,0.0,NaN,NaN